global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'raft-cluster'
    static_configs:
      # INSIDE the Docker network, everyone is on Port 8001!
      - targets: ['kv-0:8001', 'kv-1:8001', 'kv-2:8001']